Memory leak in Index for principal `null`
spring-projects/spring-session pull request #1988
Opened 2021-12-28 13:58 UTC by ruslanys

I believe this should be a solution for the reported issue.

The explanation is the following. There are only two places where we add `sessionId` into an index: [first](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L826), [second](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L864).

And the first one is under the validation: [if (principal != null)](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L824).
So, we do not create an index if a principal is `null`.

When a session changes its ID, we try to change it in the index as well.
But we do not check here that the principal is null. So, we do not check if the index exists.

In the end, instead of replacing sessionId in Index, we create a new one. And this leads to a memory leak.

Close #1987

2021-12-28 14:11 UTC, ruslanys commented
I found that this PR is the reason of the mistake: https://github.com/spring-projects/spring-session/pull/1941

2022-01-10 07:18 UTC, quaff commented
Verified this PR will fix unexpected key `spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:null` creation.

2022-01-19 14:03 UTC, eleftherias requested changes
Thanks for the PR @ruslanys! 
The changes look good to me.
Could you please squash the commits into one, and add a descriptive commit message, for example
```
Fix memory leak with null principal in Redis

Closes gh-1987
```

2022-01-19 16:31 UTC, merged

2022-01-19 16:33 UTC, eleftherias commented
Thanks @ruslanys! 
I have merged this into the main branch and I will also be backporting the fix to the 2.6.x branch, making it available in 2.6.2.

2022-01-19 16:35 UTC, ruslanys commented
Thank you @eleftherias !

2022-01-19 17:52 UTC, jebeaudet commented
@eleftherias Since this regression also reached the 2.5.x branch, could you backport it there too please? I can open a PR if you prefer.

2022-01-19 18:25 UTC, eleftherias commented
Thanks for pointing that out @jebeaudet. I will backport it to 2.5.x as well.